server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java-synthesis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 199522

  data:
    redis:
      database: 0
      host: 192.168.67.129
      port: 6379
      password: 199522
      jedis:
        pool:
          #最大连接数，负值表示没有限制
          max-active: 300
          #最大阻塞等待时间，负值表示没有限制，默认-1
          max-wait: -1
          #最大空闲连接数，默认为8
          max-idle: 10
          #最小空闲连接数，默认为0
          min-idle: 1

mybatis:
  mapper-locations: classpath:sqlMap/*.xml

